
package com.ecircle.developer.ecmapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Ecm", targetNamespace = "http://ecircle.com/developer/ecmapi")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ecm {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "version", targetNamespace = "")
    @RequestWrapper(localName = "systemGetApiVersion", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.SystemGetApiVersion")
    @ResponseWrapper(localName = "systemGetApiVersionResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.SystemGetApiVersionResponse")
    public String systemGetApiVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "version", targetNamespace = "")
    @RequestWrapper(localName = "systemGetEcmVersion", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.SystemGetEcmVersion")
    @ResponseWrapper(localName = "systemGetEcmVersionResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.SystemGetEcmVersionResponse")
    public String systemGetEcmVersion();

    /**
     * 
     * @param attributeDefinitions
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws ObjectAlreadyExistsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaCreateAttributeDefinitions", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaCreateAttributeDefinitions")
    @ResponseWrapper(localName = "metaCreateAttributeDefinitionsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaCreateAttributeDefinitionsResponse")
    public void metaCreateAttributeDefinitions(
        @WebParam(name = "attributeDefinitions", targetNamespace = "")
        List<AttributeDefinition> attributeDefinitions)
        throws InvalidParameterException_Exception, ObjectAlreadyExistsException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.AttributeDefinition>
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "attributeDefinitions", targetNamespace = "")
    @RequestWrapper(localName = "metaGetAttributeDefinitions", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaGetAttributeDefinitions")
    @ResponseWrapper(localName = "metaGetAttributeDefinitionsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaGetAttributeDefinitionsResponse")
    public List<AttributeDefinition> metaGetAttributeDefinitions()
        throws UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param attributeNames
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaArchiveAttributeDefinitions", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaArchiveAttributeDefinitions")
    @ResponseWrapper(localName = "metaArchiveAttributeDefinitionsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaArchiveAttributeDefinitionsResponse")
    public void metaArchiveAttributeDefinitions(
        @WebParam(name = "attributeNames", targetNamespace = "")
        List<String> attributeNames)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param attributeNames
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaActivateAttributeDefinitions", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaActivateAttributeDefinitions")
    @ResponseWrapper(localName = "metaActivateAttributeDefinitionsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaActivateAttributeDefinitionsResponse")
    public void metaActivateAttributeDefinitions(
        @WebParam(name = "attributeNames", targetNamespace = "")
        List<String> attributeNames)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param attributeDefinitions
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.MergeResult>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "mergeResults", targetNamespace = "")
    @RequestWrapper(localName = "metaMergeAttributeDefinitions", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaMergeAttributeDefinitions")
    @ResponseWrapper(localName = "metaMergeAttributeDefinitionsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaMergeAttributeDefinitionsResponse")
    public List<MergeResult> metaMergeAttributeDefinitions(
        @WebParam(name = "attributeDefinitions", targetNamespace = "")
        List<AttributeDefinition> attributeDefinitions)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param categories
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws ObjectAlreadyExistsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaCreateLinkCategories", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaCreateLinkCategories")
    @ResponseWrapper(localName = "metaCreateLinkCategoriesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaCreateLinkCategoriesResponse")
    public void metaCreateLinkCategories(
        @WebParam(name = "categories", targetNamespace = "")
        List<LinkCategory> categories)
        throws InvalidParameterException_Exception, ObjectAlreadyExistsException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.LinkCategory>
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "linkCategories", targetNamespace = "")
    @RequestWrapper(localName = "metaGetLinkCategories", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaGetLinkCategories")
    @ResponseWrapper(localName = "metaGetLinkCategoriesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaGetLinkCategoriesResponse")
    public List<LinkCategory> metaGetLinkCategories()
        throws UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param category
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws ObjectAlreadyExistsException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaUpdateLinkCategory", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaUpdateLinkCategory")
    @ResponseWrapper(localName = "metaUpdateLinkCategoryResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaUpdateLinkCategoryResponse")
    public void metaUpdateLinkCategory(
        @WebParam(name = "category", targetNamespace = "")
        LinkCategory category)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, ObjectAlreadyExistsException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param categoryNames
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "metaDeleteLinkCategory", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaDeleteLinkCategory")
    @ResponseWrapper(localName = "metaDeleteLinkCategoryResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MetaDeleteLinkCategoryResponse")
    public void metaDeleteLinkCategory(
        @WebParam(name = "categoryNames", targetNamespace = "")
        List<String> categoryNames)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param options
     * @return
     *     returns com.ecircle.developer.ecmapi.Group
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "group", targetNamespace = "")
    @RequestWrapper(localName = "groupClone", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupClone")
    @ResponseWrapper(localName = "groupCloneResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupCloneResponse")
    public Group groupClone(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "options", targetNamespace = "")
        GroupCloneOptions options)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns com.ecircle.developer.ecmapi.Group
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "group", targetNamespace = "")
    @RequestWrapper(localName = "groupGet", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGet")
    @ResponseWrapper(localName = "groupGetResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetResponse")
    public Group groupGet(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param attributes
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "groupIds", targetNamespace = "")
    @RequestWrapper(localName = "groupFindIdsByAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupFindIdsByAttributes")
    @ResponseWrapper(localName = "groupFindIdsByAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupFindIdsByAttributesResponse")
    public List<Long> groupFindIdsByAttributes(
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "groupSetAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupSetAttributes")
    @ResponseWrapper(localName = "groupSetAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupSetAttributesResponse")
    public void groupSetAttributes(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Attribute>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "")
    @RequestWrapper(localName = "groupGetAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetAttributes")
    @ResponseWrapper(localName = "groupGetAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetAttributesResponse")
    public List<Attribute> groupGetAttributes(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param settingsId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "groupOverrideGroupSettings", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupOverrideGroupSettings")
    @ResponseWrapper(localName = "groupOverrideGroupSettingsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupOverrideGroupSettingsResponse")
    public void groupOverrideGroupSettings(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "settingsId", targetNamespace = "")
        long settingsId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "messageIds", targetNamespace = "")
    @RequestWrapper(localName = "groupGetPreparedMessages", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetPreparedMessages")
    @ResponseWrapper(localName = "groupGetPreparedMessagesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetPreparedMessagesResponse")
    public List<Long> groupGetPreparedMessages(
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.GroupSettingsTemplate>
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "groupSettingsTemplates", targetNamespace = "")
    @RequestWrapper(localName = "groupGetAllGroupSettingsTemplates", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetAllGroupSettingsTemplates")
    @ResponseWrapper(localName = "groupGetAllGroupSettingsTemplatesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupGetAllGroupSettingsTemplatesResponse")
    public List<GroupSettingsTemplate> groupGetAllGroupSettingsTemplates()
        throws UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupIds
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.CallResult>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "archivingResults", targetNamespace = "")
    @RequestWrapper(localName = "groupArchive", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupArchive")
    @ResponseWrapper(localName = "groupArchiveResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupArchiveResponse")
    public List<CallResult> groupArchive(
        @WebParam(name = "groupIds", targetNamespace = "")
        List<Long> groupIds)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupIds
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.CallResult>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "activatingResults", targetNamespace = "")
    @RequestWrapper(localName = "groupActivate", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupActivate")
    @ResponseWrapper(localName = "groupActivateResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.GroupActivateResponse")
    public List<CallResult> groupActivate(
        @WebParam(name = "groupIds", targetNamespace = "")
        List<Long> groupIds)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @param attributes
     * @param mobileNumber
     * @return
     *     returns com.ecircle.developer.ecmapi.User
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws ObjectAlreadyExistsException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "userCreate", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserCreate")
    @ResponseWrapper(localName = "userCreateResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserCreateResponse")
    public User userCreate(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "mobileNumber", targetNamespace = "")
        String mobileNumber,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, ObjectAlreadyExistsException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @return
     *     returns com.ecircle.developer.ecmapi.User
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "userGet", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGet")
    @ResponseWrapper(localName = "userGetResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetResponse")
    public User userGet(
        @WebParam(name = "userId", targetNamespace = "")
        long userId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns com.ecircle.developer.ecmapi.User
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "userGetByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetByEmail")
    @ResponseWrapper(localName = "userGetByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetByEmailResponse")
    public User userGetByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns com.ecircle.developer.ecmapi.User
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "userGetByIdentifier", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetByIdentifier")
    @ResponseWrapper(localName = "userGetByIdentifierResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetByIdentifierResponse")
    public User userGetByIdentifier(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Attribute>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "")
    @RequestWrapper(localName = "userGetProfile", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetProfile")
    @ResponseWrapper(localName = "userGetProfileResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetProfileResponse")
    public List<Attribute> userGetProfile(
        @WebParam(name = "userId", targetNamespace = "")
        long userId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Attribute>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "")
    @RequestWrapper(localName = "userGetProfileByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetProfileByEmail")
    @ResponseWrapper(localName = "userGetProfileByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserGetProfileByEmailResponse")
    public List<Attribute> userGetProfileByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "userUpdateProfile", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserUpdateProfile")
    @ResponseWrapper(localName = "userUpdateProfileResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserUpdateProfileResponse")
    public void userUpdateProfile(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "userUpdateProfileByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserUpdateProfileByEmail")
    @ResponseWrapper(localName = "userUpdateProfileByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserUpdateProfileByEmailResponse")
    public void userUpdateProfileByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "userReplaceProfile", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserReplaceProfile")
    @ResponseWrapper(localName = "userReplaceProfileResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserReplaceProfileResponse")
    public void userReplaceProfile(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "userReplaceProfileByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserReplaceProfileByEmail")
    @ResponseWrapper(localName = "userReplaceProfileByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserReplaceProfileByEmailResponse")
    public void userReplaceProfileByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "userDelete", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserDelete")
    @ResponseWrapper(localName = "userDeleteResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.UserDeleteResponse")
    public void userDelete(
        @WebParam(name = "userId", targetNamespace = "")
        long userId)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param subscriptionMode
     * @param userId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipSubscribe", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipSubscribe")
    @ResponseWrapper(localName = "membershipSubscribeResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipSubscribeResponse")
    public void membershipSubscribe(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "subscriptionMode", targetNamespace = "")
        SubscriptionMode subscriptionMode)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param subscriptionMode
     * @param email
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipSubscribeByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipSubscribeByEmail")
    @ResponseWrapper(localName = "membershipSubscribeByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipSubscribeByEmailResponse")
    public void membershipSubscribeByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "subscriptionMode", targetNamespace = "")
        SubscriptionMode subscriptionMode)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipUnsubscribe", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUnsubscribe")
    @ResponseWrapper(localName = "membershipUnsubscribeResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUnsubscribeResponse")
    public void membershipUnsubscribe(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param email
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipUnsubscribeByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUnsubscribeByEmail")
    @ResponseWrapper(localName = "membershipUnsubscribeByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUnsubscribeByEmailResponse")
    public void membershipUnsubscribeByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @return
     *     returns com.ecircle.developer.ecmapi.Membership
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws ObjectAlreadyExistsException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "membership", targetNamespace = "")
    @RequestWrapper(localName = "membershipCreate", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipCreate")
    @ResponseWrapper(localName = "membershipCreateResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipCreateResponse")
    public Membership membershipCreate(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, ObjectAlreadyExistsException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipDelete", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipDelete")
    @ResponseWrapper(localName = "membershipDeleteResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipDeleteResponse")
    public void membershipDelete(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Membership>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "memberships", targetNamespace = "")
    @RequestWrapper(localName = "membershipFindAll", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipFindAll")
    @ResponseWrapper(localName = "membershipFindAllResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipFindAllResponse")
    public List<Membership> membershipFindAll(
        @WebParam(name = "userId", targetNamespace = "")
        long userId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Membership>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "memberships", targetNamespace = "")
    @RequestWrapper(localName = "membershipFindAllByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipFindAllByEmail")
    @ResponseWrapper(localName = "membershipFindAllByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipFindAllByEmailResponse")
    public List<Membership> membershipFindAllByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Attribute>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "")
    @RequestWrapper(localName = "membershipGetAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipGetAttributes")
    @ResponseWrapper(localName = "membershipGetAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipGetAttributesResponse")
    public List<Attribute> membershipGetAttributes(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param email
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.Attribute>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributes", targetNamespace = "")
    @RequestWrapper(localName = "membershipGetAttributesByEmail", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipGetAttributesByEmail")
    @ResponseWrapper(localName = "membershipGetAttributesByEmailResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipGetAttributesByEmailResponse")
    public List<Attribute> membershipGetAttributesByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipUpdateAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUpdateAttributes")
    @ResponseWrapper(localName = "membershipUpdateAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipUpdateAttributesResponse")
    public void membershipUpdateAttributes(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param groupId
     * @param userId
     * @param attributes
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "membershipReplaceAttributes", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipReplaceAttributes")
    @ResponseWrapper(localName = "membershipReplaceAttributesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MembershipReplaceAttributesResponse")
    public void membershipReplaceAttributes(
        @WebParam(name = "userId", targetNamespace = "")
        long userId,
        @WebParam(name = "groupId", targetNamespace = "")
        long groupId,
        @WebParam(name = "attributes", targetNamespace = "")
        List<Attribute> attributes)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param recipientId
     * @param additionalContent
     * @param messageId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "messageSendSingle", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageSendSingle")
    @ResponseWrapper(localName = "messageSendSingleResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageSendSingleResponse")
    public void messageSendSingle(
        @WebParam(name = "messageId", targetNamespace = "")
        long messageId,
        @WebParam(name = "recipientId", targetNamespace = "")
        long recipientId,
        @WebParam(name = "additionalContent", targetNamespace = "")
        MessageContent additionalContent)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param externalTransactionFormula
     * @param recipientId
     * @param additionalContent
     * @param messageId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "messageSendTransactional", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageSendTransactional")
    @ResponseWrapper(localName = "messageSendTransactionalResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageSendTransactionalResponse")
    public void messageSendTransactional(
        @WebParam(name = "messageId", targetNamespace = "")
        long messageId,
        @WebParam(name = "externalTransactionFormula", targetNamespace = "")
        String externalTransactionFormula,
        @WebParam(name = "recipientId", targetNamespace = "")
        long recipientId,
        @WebParam(name = "additionalContent", targetNamespace = "")
        MessageContent additionalContent)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param messageId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "attributeNames", targetNamespace = "")
    @RequestWrapper(localName = "messageGetUsedPersonalizations", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageGetUsedPersonalizations")
    @ResponseWrapper(localName = "messageGetUsedPersonalizationsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageGetUsedPersonalizationsResponse")
    public List<String> messageGetUsedPersonalizations(
        @WebParam(name = "messageId", targetNamespace = "")
        long messageId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param messageIds
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.CallResult>
     * @throws InvalidParameterException_Exception
     */
    @WebMethod
    @WebResult(name = "callResults", targetNamespace = "")
    @RequestWrapper(localName = "messageGetManyUsedPersonalizations", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageGetManyUsedPersonalizations")
    @ResponseWrapper(localName = "messageGetManyUsedPersonalizationsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageGetManyUsedPersonalizationsResponse")
    public List<CallResult> messageGetManyUsedPersonalizations(
        @WebParam(name = "messageIds", targetNamespace = "")
        List<String> messageIds)
        throws InvalidParameterException_Exception
    ;

    /**
     * 
     * @param messageId
     * @return
     *     returns com.ecircle.developer.ecmapi.CallResult
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "validationResult", targetNamespace = "")
    @RequestWrapper(localName = "messageValidate", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidate")
    @ResponseWrapper(localName = "messageValidateResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidateResponse")
    public CallResult messageValidate(
        @WebParam(name = "messageId", targetNamespace = "")
        String messageId)
        throws UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param messageIds
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.MethodResult>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "validationResults", targetNamespace = "")
    @RequestWrapper(localName = "messageValidateList", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidateList")
    @ResponseWrapper(localName = "messageValidateListResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidateListResponse")
    public List<MethodResult> messageValidateList(
        @WebParam(name = "messageIds", targetNamespace = "")
        List<Long> messageIds)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param messageIds
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.CallResult>
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "validationResults", targetNamespace = "")
    @RequestWrapper(localName = "messageValidateMany", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidateMany")
    @ResponseWrapper(localName = "messageValidateManyResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.MessageValidateManyResponse")
    public List<CallResult> messageValidateMany(
        @WebParam(name = "messageIds", targetNamespace = "")
        List<Long> messageIds)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param landingpageId
     * @return
     *     returns java.lang.String
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws NoSuchObjectException_Exception
     */
    @WebMethod
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "landingpageGetStatus", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageGetStatus")
    @ResponseWrapper(localName = "landingpageGetStatusResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageGetStatusResponse")
    public String landingpageGetStatus(
        @WebParam(name = "landingpageId", targetNamespace = "")
        long landingpageId)
        throws InvalidParameterException_Exception, NoSuchObjectException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param landingpageId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws LandingpageException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "landingpageDelete", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageDelete")
    @ResponseWrapper(localName = "landingpageDeleteResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageDeleteResponse")
    public void landingpageDelete(
        @WebParam(name = "landingpageId", targetNamespace = "")
        long landingpageId)
        throws InvalidParameterException_Exception, LandingpageException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param landingpageIds
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws LandingpageException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "landingpageDeleteMany", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageDeleteMany")
    @ResponseWrapper(localName = "landingpageDeleteManyResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.LandingpageDeleteManyResponse")
    public void landingpageDeleteMany(
        @WebParam(name = "landingpageIds", targetNamespace = "")
        List<Long> landingpageIds)
        throws InvalidParameterException_Exception, LandingpageException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param topic
     * @param arguments
     * @return
     *     returns java.lang.String
     * @throws UnexpectedErrorException_Exception
     * @throws AsyncException_Exception
     */
    @WebMethod
    @WebResult(name = "queueId", targetNamespace = "")
    @RequestWrapper(localName = "asyncSubmit", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncSubmit")
    @ResponseWrapper(localName = "asyncSubmitResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncSubmitResponse")
    public String asyncSubmit(
        @WebParam(name = "topic", targetNamespace = "")
        String topic,
        @WebParam(name = "arguments", targetNamespace = "")
        List<Attribute> arguments)
        throws AsyncException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws AsyncException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "topics", targetNamespace = "")
    @RequestWrapper(localName = "asyncListTopics", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncListTopics")
    @ResponseWrapper(localName = "asyncListTopicsResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncListTopicsResponse")
    public List<String> asyncListTopics()
        throws AsyncException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param limit
     * @param topic
     * @return
     *     returns java.util.List<com.ecircle.developer.ecmapi.AsyncResult>
     * @throws UnexpectedErrorException_Exception
     * @throws AsyncException_Exception
     */
    @WebMethod
    @WebResult(name = "results", targetNamespace = "")
    @RequestWrapper(localName = "asyncPoll", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncPoll")
    @ResponseWrapper(localName = "asyncPollResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncPollResponse")
    public List<AsyncResult> asyncPoll(
        @WebParam(name = "topic", targetNamespace = "")
        String topic,
        @WebParam(name = "limit", targetNamespace = "")
        int limit)
        throws AsyncException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param topic
     * @return
     *     returns long
     * @throws InvalidParameterException_Exception
     * @throws AsyncException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "puts", targetNamespace = "")
    @RequestWrapper(localName = "asyncGetSubmitCount", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetSubmitCount")
    @ResponseWrapper(localName = "asyncGetSubmitCountResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetSubmitCountResponse")
    public long asyncGetSubmitCount(
        @WebParam(name = "topic", targetNamespace = "")
        String topic)
        throws AsyncException_Exception, InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param topic
     * @return
     *     returns long
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws AsyncException_Exception
     */
    @WebMethod
    @WebResult(name = "polls", targetNamespace = "")
    @RequestWrapper(localName = "asyncGetPollCount", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetPollCount")
    @ResponseWrapper(localName = "asyncGetPollCountResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetPollCountResponse")
    public long asyncGetPollCount(
        @WebParam(name = "topic", targetNamespace = "")
        String topic)
        throws AsyncException_Exception, InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param topic
     * @return
     *     returns int
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws AsyncException_Exception
     */
    @WebMethod
    @WebResult(name = "capacity", targetNamespace = "")
    @RequestWrapper(localName = "asyncGetRemainingCapacity", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetRemainingCapacity")
    @ResponseWrapper(localName = "asyncGetRemainingCapacityResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.AsyncGetRemainingCapacityResponse")
    public int asyncGetRemainingCapacity(
        @WebParam(name = "topic", targetNamespace = "")
        String topic)
        throws AsyncException_Exception, InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param content
     * @return
     *     returns com.ecircle.developer.ecmapi.AttachmentReference
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @WebResult(name = "contentReference", targetNamespace = "")
    @RequestWrapper(localName = "contentStore", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.ContentStore")
    @ResponseWrapper(localName = "contentStoreResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.ContentStoreResponse")
    public AttachmentReference contentStore(
        @WebParam(name = "content", targetNamespace = "")
        Attachment content)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param contentId
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "contentDelete", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.ContentDelete")
    @ResponseWrapper(localName = "contentDeleteResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.ContentDeleteResponse")
    public void contentDelete(
        @WebParam(name = "contentId", targetNamespace = "")
        String contentId)
        throws InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

    /**
     * 
     * @param messages
     * @throws InvalidParameterException_Exception
     * @throws UnexpectedErrorException_Exception
     * @throws BatchException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "emailSendMessages", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.EmailSendMessages")
    @ResponseWrapper(localName = "emailSendMessagesResponse", targetNamespace = "http://ecircle.com/developer/ecmapi", className = "com.ecircle.developer.ecmapi.EmailSendMessagesResponse")
    public void emailSendMessages(
        @WebParam(name = "messages", targetNamespace = "")
        List<Message> messages)
        throws BatchException_Exception, InvalidParameterException_Exception, UnexpectedErrorException_Exception
    ;

}
